name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Generate fragments
        run: |
          git checkout -B pdf
          pip install -r requirements.txt
          python generate_tex.py
      - name: Upload fragments to branch pdf
        uses: stefanzweifel/git-auto-commit-action@v4.5.1
        with:
          commit_user_name: "Huy-Ngo"
          commit_user_email: "duchuy29092000@gmail.com"
          commit_author: "Huy-Ngo <duchuy29092000@gmail.com>"
          commit_message: "Generate LaTeX fragments"
          push_options: '--force'
          branch: png
      - name: Download TeXLive
        run: |
          echo "deb http://ftp.fi.debian.org/debian/ buster main contrib non-free" >> /etc/apt/sources.list.d
          echo "sudo deb-src http://ftp.fi.debian.org/debian/ buster main contrib non-free" >> /etc/apt/sources.list.d
          sudo apt install icc-profiles
          sudo apt install texlive-full
      - name: Compile LaTeX
        run: |
          pdflatex sample.tex
          biber sample.bcf
          pdflatex sample.tex
